# encoding: UTF-8

defaults: &defaults
  status: open #| close

  api_key: xxxxxxxxxxxxxxxxxxxxxxxxxx
  host: localhost
  port: 3001
  secure: 443

development: &development
  <<: *defaults

test:
  <<: *development

production:
  <<: *development

